### ISSUE TITLE
Play/stop on mouse hover ?

### ISSUE THREAD

**Issue by tk-master** [jeankassio/JK-GIF-Player-jQuery#1]
Could you please provide an example on how to play/stop a gif with mouse hover instead of click?

Ideally I would also like the hover play to (optionally) ignore the loops parameter so it keeps playing indefinitely when hovered.

Thanks a lot.

**Comment by jeankassio** [comment]
Complete answer to yout question here --> https://codepen.io/jeankassio/pen/yLGrJGe

```js
$(".gifimage").JKGifPlayer({
      autopause:false
  });

$(document).on('mouseover mouseout', '.gifimage', function(e) { 
    
  $(".gifimage").PlayStop_Gif();
  
});
```
